### ISSUE TITLE
change static abbreviation from `{% static "" %}` to `{% static '' %}`

### ISSUE THREAD

**Issue by eromoe** [squ1b3r/Djaneiro#100]
I'd like to use  
```
<script src="{% static 'share/plugins/jQuery/jQuery-2.1.4.min.js' %}" type="text/javascript"></script>
```
 instead of 
```
<script src="{% static "share/plugins/jQuery/jQuery-2.1.4.min.js" %}" type="text/javascript"></script>
```

I don't want so much double quotes in one line.

**Comment by squ1b3r** [comment]
Well, you can fork the plugin and change what you like. Since django renders it's template tags first and then put result in html and renders it there is no issues with using double quites. It also brings some concistenty in my oppinion. And if you check the official Django doc [here](https://docs.djangoproject.com/en/1.9/ref/templates/builtins/#static) it uses double quotes exactly the same way. So. Sorry, but won't happen.
